// Code generated by MockGen. DO NOT EDIT.
// Source: file_usecase.go
//
// Generated by this command:
//
//	mockgen -source=file_usecase.go -destination=mock/file_usecase_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/wingarc-ktq/speckit-workshop-server/services/files/internal/domain"
	usecase "github.com/wingarc-ktq/speckit-workshop-server/services/files/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockFileUsecase is a mock of FileUsecase interface.
type MockFileUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFileUsecaseMockRecorder
	isgomock struct{}
}

// MockFileUsecaseMockRecorder is the mock recorder for MockFileUsecase.
type MockFileUsecaseMockRecorder struct {
	mock *MockFileUsecase
}

// NewMockFileUsecase creates a new mock instance.
func NewMockFileUsecase(ctrl *gomock.Controller) *MockFileUsecase {
	mock := &MockFileUsecase{ctrl: ctrl}
	mock.recorder = &MockFileUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUsecase) EXPECT() *MockFileUsecaseMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockFileUsecase) DownloadFile(ctx context.Context, id uuid.UUID) (*usecase.DownloadOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, id)
	ret0, _ := ret[0].(*usecase.DownloadOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFileUsecaseMockRecorder) DownloadFile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFileUsecase)(nil).DownloadFile), ctx, id)
}

// GetFile mocks base method.
func (m *MockFileUsecase) GetFile(ctx context.Context, id uuid.UUID) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile", ctx, id)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFile indicates an expected call of GetFile.
func (mr *MockFileUsecaseMockRecorder) GetFile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockFileUsecase)(nil).GetFile), ctx, id)
}

// ListFiles mocks base method.
func (m *MockFileUsecase) ListFiles(ctx context.Context, params usecase.ListFilesParams) ([]*domain.File, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFiles", ctx, params)
	ret0, _ := ret[0].([]*domain.File)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockFileUsecaseMockRecorder) ListFiles(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockFileUsecase)(nil).ListFiles), ctx, params)
}

// UploadFile mocks base method.
func (m *MockFileUsecase) UploadFile(ctx context.Context, input usecase.UploadFileInput) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, input)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileUsecaseMockRecorder) UploadFile(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileUsecase)(nil).UploadFile), ctx, input)
}
