// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, name, size, mime_type, description, storage_key, tag_ids)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, size, mime_type, description, storage_key, tag_ids, uploaded_at
`

type CreateFileParams struct {
	ID          pgtype.UUID
	Name        string
	Size        int64
	MimeType    string
	Description string
	StorageKey  string
	TagIds      []pgtype.UUID
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.Name,
		arg.Size,
		arg.MimeType,
		arg.Description,
		arg.StorageKey,
		arg.TagIds,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.MimeType,
		&i.Description,
		&i.StorageKey,
		&i.TagIds,
		&i.UploadedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, name, size, mime_type, description, storage_key, tag_ids, uploaded_at
FROM files
WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Size,
		&i.MimeType,
		&i.Description,
		&i.StorageKey,
		&i.TagIds,
		&i.UploadedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT
    id, name, size, mime_type, description, storage_key, tag_ids, uploaded_at,
    COUNT(*) OVER() AS total_count
FROM files
WHERE
    ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
    AND ($2::uuid[] IS NULL OR tag_ids && $2::uuid[])
ORDER BY uploaded_at DESC
LIMIT $4
OFFSET $3
`

type ListFilesParams struct {
	Search *string
	TagIds []pgtype.UUID
	Off    int32
	Lim    int32
}

type ListFilesRow struct {
	ID          pgtype.UUID
	Name        string
	Size        int64
	MimeType    string
	Description string
	StorageKey  string
	TagIds      []pgtype.UUID
	UploadedAt  pgtype.Timestamptz
	TotalCount  int64
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.Query(ctx, listFiles,
		arg.Search,
		arg.TagIds,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Size,
			&i.MimeType,
			&i.Description,
			&i.StorageKey,
			&i.TagIds,
			&i.UploadedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
