// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*)::bigint AS total
FROM files
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountFiles(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countFiles, dollar_1)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, name, mime_type, description, storage_key, size, uploaded_at
FROM files
WHERE id = $1
`

type GetFileByIDRow struct {
	ID          pgtype.UUID
	Name        string
	MimeType    string
	Description *string
	StorageKey  string
	Size        int64
	UploadedAt  pgtype.Timestamptz
}

func (q *Queries) GetFileByID(ctx context.Context, id pgtype.UUID) (GetFileByIDRow, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i GetFileByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Description,
		&i.StorageKey,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}

const getFileTags = `-- name: GetFileTags :many
SELECT tag_id
FROM file_tags
WHERE file_id = $1
`

func (q *Queries) GetFileTags(ctx context.Context, fileID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getFileTags, fileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFile = `-- name: InsertFile :one
INSERT INTO files (id, name, mime_type, description, storage_key, size, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, name, mime_type, description, storage_key, size, uploaded_at
`

type InsertFileParams struct {
	ID          pgtype.UUID
	Name        string
	MimeType    string
	Description *string
	StorageKey  string
	Size        int64
}

type InsertFileRow struct {
	ID          pgtype.UUID
	Name        string
	MimeType    string
	Description *string
	StorageKey  string
	Size        int64
	UploadedAt  pgtype.Timestamptz
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (InsertFileRow, error) {
	row := q.db.QueryRow(ctx, insertFile,
		arg.ID,
		arg.Name,
		arg.MimeType,
		arg.Description,
		arg.StorageKey,
		arg.Size,
	)
	var i InsertFileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MimeType,
		&i.Description,
		&i.StorageKey,
		&i.Size,
		&i.UploadedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, name, mime_type, description, storage_key, size, uploaded_at
FROM files
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%')
ORDER BY uploaded_at DESC
LIMIT $2::bigint OFFSET $3::bigint
`

type ListFilesParams struct {
	Column1 string
	Column2 int64
	Column3 int64
}

type ListFilesRow struct {
	ID          pgtype.UUID
	Name        string
	MimeType    string
	Description *string
	StorageKey  string
	Size        int64
	UploadedAt  pgtype.Timestamptz
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]ListFilesRow, error) {
	rows, err := q.db.Query(ctx, listFiles, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFilesRow
	for rows.Next() {
		var i ListFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MimeType,
			&i.Description,
			&i.StorageKey,
			&i.Size,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
