// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*)::int
FROM files
WHERE owner_user_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
`

type CountFilesParams struct {
	OwnerUserID pgtype.UUID
	Column2     string
}

func (q *Queries) CountFiles(ctx context.Context, arg CountFilesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countFiles, arg.OwnerUserID, arg.Column2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, owner_user_id, name, size, mime_type, description, uploaded_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
RETURNING id, owner_user_id, name, size, mime_type, description, uploaded_at
`

type CreateFileParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	Size        int64
	MimeType    string
	Description *string
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Size,
		arg.MimeType,
		arg.Description,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Size,
		&i.MimeType,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE id = $1 AND owner_user_id = $2
`

type DeleteFileParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.Exec(ctx, deleteFile, arg.ID, arg.OwnerUserID)
	return err
}

const deleteFilesByIDs = `-- name: DeleteFilesByIDs :exec
DELETE FROM files
WHERE owner_user_id = $1
  AND id = ANY($2::uuid[])
`

type DeleteFilesByIDsParams struct {
	OwnerUserID pgtype.UUID
	Column2     []pgtype.UUID
}

func (q *Queries) DeleteFilesByIDs(ctx context.Context, arg DeleteFilesByIDsParams) error {
	_, err := q.db.Exec(ctx, deleteFilesByIDs, arg.OwnerUserID, arg.Column2)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, owner_user_id, name, size, mime_type, description, uploaded_at
FROM files
WHERE id = $1 AND owner_user_id = $2
`

type GetFileByIDParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, arg.ID, arg.OwnerUserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Size,
		&i.MimeType,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}

const listFiles = `-- name: ListFiles :many
SELECT id, owner_user_id, name, size, mime_type, description, uploaded_at
FROM files
WHERE owner_user_id = $1
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%')
ORDER BY uploaded_at DESC
LIMIT $3 OFFSET $4
`

type ListFilesParams struct {
	OwnerUserID pgtype.UUID
	Column2     string
	Limit       int32
	Offset      int32
}

func (q *Queries) ListFiles(ctx context.Context, arg ListFilesParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFiles,
		arg.OwnerUserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Name,
			&i.Size,
			&i.MimeType,
			&i.Description,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileMetadata = `-- name: UpdateFileMetadata :one
UPDATE files
SET name = $3,
    description = $4,
    uploaded_at = NOW()
WHERE id = $1 AND owner_user_id = $2
RETURNING id, owner_user_id, name, size, mime_type, description, uploaded_at
`

type UpdateFileMetadataParams struct {
	ID          pgtype.UUID
	OwnerUserID pgtype.UUID
	Name        string
	Description *string
}

func (q *Queries) UpdateFileMetadata(ctx context.Context, arg UpdateFileMetadataParams) (File, error) {
	row := q.db.QueryRow(ctx, updateFileMetadata,
		arg.ID,
		arg.OwnerUserID,
		arg.Name,
		arg.Description,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Size,
		&i.MimeType,
		&i.Description,
		&i.UploadedAt,
	)
	return i, err
}
