// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type TagColor string

const (
	TagColorBlue   TagColor = "blue"
	TagColorRed    TagColor = "red"
	TagColorYellow TagColor = "yellow"
	TagColorGreen  TagColor = "green"
	TagColorPurple TagColor = "purple"
	TagColorOrange TagColor = "orange"
	TagColorGray   TagColor = "gray"
)

func (e *TagColor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagColor(s)
	case string:
		*e = TagColor(s)
	default:
		return fmt.Errorf("unsupported scan type for TagColor: %T", src)
	}
	return nil
}

type NullTagColor struct {
	TagColor TagColor
	Valid    bool // Valid is true if TagColor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTagColor) Scan(value interface{}) error {
	if value == nil {
		ns.TagColor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TagColor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTagColor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TagColor), nil
}

type File struct {
	ID          pgtype.UUID
	Name        string
	Size        int64
	MimeType    string
	Description *string
	StorageKey  string
	UploadedAt  pgtype.Timestamptz
}

type FileTag struct {
	FileID pgtype.UUID
	TagID  pgtype.UUID
}

type Tag struct {
	ID        pgtype.UUID
	Name      string
	Color     TagColor
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
