// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type File struct {
	ID          pgtype.UUID
	Name        string
	Size        int64
	MimeType    string
	Description string
	StorageKey  string
	TagIds      []pgtype.UUID
	UploadedAt  pgtype.Timestamptz
}
