// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFileTags = `-- name: DeleteFileTags :exec
DELETE FROM file_tags
WHERE file_id = $1
`

func (q *Queries) DeleteFileTags(ctx context.Context, fileID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFileTags, fileID)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, name, color, created_at, updated_at
FROM tags
WHERE id = $1
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (Tag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFileTag = `-- name: InsertFileTag :exec
INSERT INTO file_tags (file_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertFileTagParams struct {
	FileID pgtype.UUID
	TagID  pgtype.UUID
}

func (q *Queries) InsertFileTag(ctx context.Context, arg InsertFileTagParams) error {
	_, err := q.db.Exec(ctx, insertFileTag, arg.FileID, arg.TagID)
	return err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tags (id, name, color, created_at, updated_at)
VALUES ($1, $2, $3, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  color = EXCLUDED.color,
  updated_at = NOW()
RETURNING id, name, color, created_at, updated_at
`

type UpsertTagParams struct {
	ID    pgtype.UUID
	Name  string
	Color TagColor
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, upsertTag, arg.ID, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
